### ISSUE TITLE
error loading checkpoint in synthesis time

### ISSUE THREAD

**Issue by navidnadery** [Rayhane-mamah/Tacotron-2#64] opened 2018-06-06 16:03 UTC
Hi and thank for publishing Tacotron-2.
I trained network using  `python train.py --model='Both'` then tried to synthesis from checkpoints using python synthesize.py --model='Tacotron-2' and run to this error:

NotFoundError (see above for traceback): Key model_1/model/ResidualConv1dGLU_0/residual_block_cin_conv/bias_residual_block_cin_conv/ExponentialMovingAverage not found in checkpoint

**Comment by a3626a** [comment] 2018-06-08 11:06
I found similar error.

In my case,
`model_1/model/ResidualConv1dGLU_0/residual_block_cin_conv/bias_residual_block_cin_conv/ExponentialMovingAverage` was saved as `model_1/model_1/model/ResidualConv1dGLU_0/residual_block_cin_conv/bias_residual_block_cin_conv/ExponentialMovingAverage`.

You can edit your `create_shadow_saver` to load variables with those names.

**Comment by navidnadery** [comment] 2018-06-10 15:42
@a3626a Thank you very much.
But I ran again to see whats happened, and I found this error during training: 
"tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled"
exactly after: "Tacotron training complete after 85000 global steps!"

**Comment by a3626a** [comment] 2018-06-10 15:53
https://github.com/Rayhane-mamah/Tacotron-2/blob/e2f9780b18648b8d0b671e1c85dd95d20d6f8553/tacotron/train.py#L296-L297

Check your command line argument `tacotron_train_steps`

**Comment by navidnadery** [comment] 2018-06-10 15:58
Yeah, I got it. Thank you very much. I really appreciate.

**Comment by navidnadery** [comment] 2018-06-18 07:45
Hi again.
@a3626a Thank you, I used your help (editing names of variables from model_1 to model) and it loaded those models without problem, but it errors for models in encoder and decoder parts of wavenet. I've checked variables during training and non of the variables are found in training variables during training. How can I handle this?
Here is an example of the error:
> model/model/inference/decoder/Location_Sensitive_Attention/attention_bias/ExponentialMovingAverage

**Comment by a3626a** [comment] 2018-06-18 10:02
Inside your checkpoint, trainable variables (`tf.trainable_variabels()`) are not saved, their Exponential Moving Averages are saved.

Can you explain what you are trying to do?
1) Load trained model and synthesis
2) Load trained model and continue training
3) Just to start training

**Comment by navidnadery** [comment] 2018-06-18 10:31
1 and 2 both have been tried. Actually, I want 2.

**Comment by victorkohler** [comment] 2018-07-19 15:48
Hello! I'm getting the same errors as described above. 

When loading the trained model and running synthesis  using `--model='Both'` it's looking for "model_1/model/..." rather than "model/model/..."

I updated create_shadow_saver to replace "model_1" with "model" but then run into the following error: 
`NotFoundError (see above for traceback): Key model/model/inference/decoder/Location_Sensitive_Attention/attention_bias/ExponentialMovingAverage not found in checkpoint`

I usde print_tensors_in_checkpoint_file and as far as I can tell this name is not stored in the checkpoint file at all.

Anyone know what is going on here? Thanks!

**Comment by navidnadery** [comment] 2018-07-20 09:07
create_shadow_saver selects some variables for saving. You can comment this part and use tf.saver.save to save whole tensor variables. Then you have to change synthesis part for loading saved tensors.

**Comment by Rayhane-mamah** [comment] 2018-08-04 18:26
Hello, I can't quite manage to reproduce with latest commit, I am closing this as I believe it was fixed meanwhile. If the problem persists feel free to reopen! 

I also disabled training with "Both" as it seems to be causing problems for many people, so now simply use "Tacotron-2" for both models.

**Closed by Rayhane-mamah** 2018-08-04 18:26 UTC
