### ISSUE TITLE
syntesize wavenet /generate

### ISSUE THREAD

**Issue by ilhamprayudha** [Rayhane-mamah/Tacotron-2#108] opened 2018-07-24 03:39 UTC
how to generate test or sample ?

python3 synthesize.py --model='WaveNet' --name=WaveNet --output_dir=waveljnew
i try this code to synthesize checkpoint wavenet . and this is result
[result.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2221879/result.zip)
is there a step that is passed ?

**Comment by ilhamprayudha** [comment] 2018-07-30 01:38
@Yeongtae 
has it been fixed?

**Comment by Yeongtae** [comment] 2018-07-31 03:09
@ilhamprayudha 
There is a solution about your problem.
https://github.com/Rayhane-mamah/Tacotron-2/files/2145382/models.tar.gz,

Change parameters in hparams.py
input_type="mulaw",
quantize_channels=256, # 65536 (16-bit) (raw) or 256 (8-bit) (mulaw or mulaw-quantize) // number of classes = 256 <=> mu = 255

**Comment by ilhamprayudha** [comment] 2018-07-31 05:08
@Yeongtae this solution replace what ? and how to using this solution

**Comment by Rayhane-mamah** [comment] 2018-08-04 17:11
Hello, Like @Yeongtae said, there were bugs. They are fixed in latest commit.
In any case this issue is duplicate of:
https://github.com/Rayhane-mamah/Tacotron-2/issues/57

I am closing this, if you encounter the same issue with latest commit please let me know.

**Closed by Rayhane-mamah** 2018-08-04 17:11 UTC
