### ISSUE TITLE
Evaluate a string directly

### ISSUE THREAD

**Issue by seatonullberg** [Rayhane-mamah/Tacotron-2#28] opened 2018-04-23 04:13 UTC
Hi, thank you for building this implementation. I have found it to be the easiest to work with of any Tacotron model. I'm currently at 25,000 steps and the checkpoint examples sound good so I would like to run some custom evaluations. Is there a safe way to pass in a string directly and output a .wav? From initial inspection it looks like I might be able to do this by overwriting hparams.sentences, but I would prefer to bypass the plotting and logging that happens during normal operation for enhanced speed. Thanks for all the hard work!

**Comment by seatonullberg** [comment] 2018-04-23 12:32
A live interaction is what I was looking for. My application will have inputs come one at a time and play the .wav file upon generation and then delete it before the next one is made. Ideally, the .wav would be streaming directly without the I/O time, but I know that opens up an extra set of challenges.

**Comment by Rayhane-mamah** [comment] 2018-04-23 14:16
Sure thing I'll add it for next commit.

Thanks for your patience.

**Comment by Rayhane-mamah** [comment] 2018-05-20 20:09
Well a lot changed since the latest version of the repo so it will be a little hard to pinpoint where the OOM is coming from, you could use [max_mel_frames](https://github.com/Rayhane-mamah/Tacotron-2/blob/master/hparams.py#L23) argument to discard data that are too long (I don't like it very much).

As an alternative, you can easily set [outputs_per_step](https://github.com/Rayhane-mamah/Tacotron-2/blob/master/hparams.py#L54) to 2 without loosing much quality (also compatible with Wavenet if needed). This will also allow for faster computation and gives the opportunity to use higher batch_size.

I am really unsure about what's causing the OOM considering recent changes I made on the project affected the actual RAM not the VRAM of the GPU..

**Comment by seatonullberg** [comment] 2018-05-22 23:26
Sorry, one more issue! I have roughly trained a new Tacotron model and tried to use the live mode, however, I get the following error:
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [80] rhs shape= [160]
Could this have something to do with me using 2 outputs_per_step in training or is that totally unrelated?

**Comment by Rayhane-mamah** [comment] 2018-08-04 18:57
I am sorry I was not able to reproduce, I suppose you changed some hyperparameter between train and test times? I am closing the issue for now hoping you solved this, if not, please reopen with details about your training and test procedures.

**Closed by Rayhane-mamah** 2018-08-04 18:57 UTC
