### ISSUE TITLE
Where is the wavenet input "tacotron_output/gta/map.txt"?

### ISSUE THREAD

**Issue by begeekmyfriend** [Rayhane-mamah/Tacotron-2#52] opened 2018-05-25 02:47 UTC
I have trained out a `Tacotron` model and  the directory structure is as follows:
	tacotron_output
	├──eval
	│              ├──map.txt
	│              └──*.npy
	└──logs-eval
		        ├──plots
		        └──wavs
And then I wanted to train the `WaveNet` model but it confused me that I need the input `tacotron_output/gta/map.txt`. Where can I find it? Is it `tacotron_output/eval/map.txt`? But the matadata fetched in the feeder seemed not the proper one.

**Comment by Rayhane-mamah** [comment] 2018-05-25 03:13
You need to make a GTA synthesis using the Tacotron model. If you trained
using "Tacotron-2" or "Both" as model name, did it not launch automatically?

**Comment by begeekmyfriend** [comment] 2018-05-25 03:27
@Rayhane-mamah It still throws exception in `feeder.py` after I merged your latest commit. It seems the `args.input_path` kept the old one.
> Traceback (most recent call last):
  File "train.py", line 83, in <module>
    main()
  File "train.py", line 75, in main
    wavenet_train(args, log_dir, hparams, args.wavenet_input)
  File "/home/leoma/Tacotron-2/wavenet_vocoder/train.py", line 243, in wavenet_train
    train(log_dir, args, hparams, input_path)
  File "/home/leoma/Tacotron-2/wavenet_vocoder/train.py", line 163, in train
    feeder = Feeder(coord, input_path, args.base_dir, hparams)
  File "/home/leoma/Tacotron-2/wavenet_vocoder/feeder.py", line 36, in __init__
    with open(metadata_filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tacotron_output/gta/map.txt'

**Comment by Rayhane-mamah** [comment] 2018-05-25 03:34
I believe the correct way to run the synthesis is:
> python synthesize.py --mode=synthesis --GTA=True --model='Tacotron'

Since (ec0cd50d24d7f5561f696a78d0cd47d5a2a14a43) I have maid the "eval" mode default behavior for synthesis assuming "Tacotron-2" will be default behavior for synthesis in the future, so to generate using GTA, one must explicitly set `mode=synthesis`

It will not work if you use "Tacotron-2" For synthesis on all dataset because it supposes you want to generate using Both Tacotron and Wavenet, using `model=Tacotron` will do the task you wanna achieve. I will retest the entire pipeline later to check if this is still a problem..

**Comment by MXGray** [comment] 2018-05-25 03:47
Solved similar problems by placing absolute paths, especially for base_dir.
I'm using Ubuntu 16.04, Python 3.5, Tensorflow 1.6 and Keras 2.0.2. All the rest of the libraries are the exact versions required (the ones I mentioned earlier are ones whose versions aren't explicitly mentioned in this repo).
Encountered the following problems before I did this:
-  Can't find metadata.csv during preprocessing; and
-  griffin_lim issue (missing hparam arg) during training, specifically right after the training script created a checkpoint and was doing eval.
P.S.  I'm using 'Tacotron-2' (both) for training.

**Comment by Rayhane-mamah** [comment] 2018-05-26 20:26
@MXGray please verify that this line is not commented in your train.py:
https://github.com/Rayhane-mamah/Tacotron-2/blob/fb5564b7584ae0dc62ffecaa89d463ff24a3c251/train.py#L34

Run the training again with Tacotron-2, it will skip Feature Prediction Network training whem it finds the checkpoint. It should run GTA synthesis then wavenet training. Tell me how it goes

**Comment by MXGray** [comment] 2018-05-26 20:46
@Rayhane-mamah
Thanks! Seems to be working now - Used --model='Tacotron-2', and training skipped immediately to wavenet training after detecting the latest feature prediction checkpoint (50KS).
It's now at 3% synthesis; and
Here's what I de-commented and commented in train.py:

	input_path = tacotron_synthesize(args, hparams, checkpoint)
	#input_path = 'tacotron_output/gta/map.txt'

Cheers! :)

**Comment by Rayhane-mamah** [comment] 2018-05-26 20:48
Yeah these lines were wrong in previous version of the repo but are fixed now. Feel free to share your results with Wavenet once it's fixed

**Comment by MXGray** [comment] 2018-05-29 18:07
@Rayhane-mamah
Been encountering errors while trying to synthesize custom text using the saved checkpoints for both the encoder network and the wavenet vocoder; and
My CLI command is:

python synthesize.py --model='Tacotron-2' --mode='eval'

And, I get this:

synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
synthesize.py, line 33, in synthesize
wavenet_synthesize(args, hparams, wave_checkpoint) 
/wavenet_vocoder/synthesize.py", line 78, in wavenet_synthesize
run_synthesis(args, checkpoint_path, output_dir, hparams) 
/wavenet_vocoder/synthesize.py", line 19, in run_synthesis synth.load(checkpoint_path, hparams)
/wavenet_vocoder/synthesizer.py", line 27, in load  sh_saver = create_shadow_saver(self.model)
/wavenet_vocoder/train.py", line 53, in create_shadow_saver return tf.train.Saver(shadow_dict, max_to_keep=5)
/tensorflow/python/training/saver.py", line 1293, in __init__ self.build() 
/tensorflow/python/training/saver.py", line 1302, in build self._build(self._filename, build_save=True, build_restore=True)
/tensorflow/python/training/saver.py", line 1339, in _build build_save=build_save, build_restore=build_restore)
/tensorflow/python/training/saver.py", line 796, in _build_internal restore_sequentially, reshape)
/tensorflow/python/training/saver.py", line 449, in _AddRestoreOps restore_sequentially)
/tensorflow/python/training/saver.py", line 847, in bulk_restore return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
/tensorflow/python/ops/gen_io_ops.py", line 1030, in restore_v2
shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper op_def=op_def)
/tensorflow/python/framework/ops.py", line 3271, in create_op op_def=op_def)
/tensorflow/python/framework/ops.py", line 1650, in __init__ self._traceback = self._graph._extract_stack()  # pylint: disable=protected-accessNotFoundError (see above for traceback): Key model_1/model/ResidualConv1dGLU_0/residual_block_cin_conv/bias_residual_block_cin_conv/ExponentialMovingAverage not found in checkpoint
[[Node: model_1/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_model_1/save/Const_0_0, model_1/save/RestoreV2/tensor_names,model_1/save/RestoreV2/shape_and_slices)]]

What could be the problem?

**Comment by Rayhane-mamah** [comment] 2018-05-29 21:42
Hello again @MXGray, yes I have encountered same problems too, didn't find time to upload corrections today, I will upload it in a couple of minutes

**Comment by MXGray** [comment] 2018-05-30 08:19
Hi @Rayhane-mamah,
Just wanted to kindly ask if you've already uploaded the corrected files?
Please advise. Thanks! :)

**Comment by Rayhane-mamah** [comment] 2018-05-30 08:28
Yes I did, the bug is mainly due to Exponential Moving Average requesting checkpoints from a wrong scope at synthesis time. I don't quite remember which scopes were wrong, but this issue is supposed to be fixed 2 commits ago, naturally if you're using a model trained before the scopes bug was fixed, checkpoint files will still have wrong scopes in them..

I am hoping you didn't train the Wavenet for too long..

**Comment by cuicp** [comment] 2018-06-22 02:15
i trained the model with the latest code(e2f9780b18648b8d0b671e1c85dd95d20d6f8553), but when i executed 'python synthesize.py', the WaveNet model still load failed， the details #82

**Comment by v-yunbin** [comment] 2018-06-25 06:28
@MXGray 
when i train with tacotron2: 
python train.py --model='Tacotron-2'
it stuck in wavenet train.

[2018-06-25 12:49:19.476]  No model to load at logs-Tacotron-2/wave_pretrained/
[2018-06-25 12:49:19.550]  
Generated 62 test batches of size 1 in 0.073 sec
[2018-06-25 12:49:19.553]  
Generated 32 train batches of size 2 in 0.076 sec
[2018-06-25 12:49:23.835]  Exiting due to Exception: Conv2DCustomBackpropInputOp only supports NHWC.
	 [[Node: model_1/inference/conv2d_transpose/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 16], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model_1/inference/conv2d_transpose/stack, model/inference/conv2d_transpose/kernel/read, model_1/inference/ExpandDims_1)]]

Caused by op 'model_1/inference/conv2d_transpose/conv2d_transpose', defined at:
  File "train.py", line 127, in <module>
    main()
  File "train.py", line 121, in main
    train(args, log_dir, hparams)
  File "train.py", line 75, in train
    checkpoint = wavenet_train(args, log_dir, hparams, input_path)
  File "/data02/zhangyb/Tacotron-2/wavenet_vocoder/train.py", line 244, in wavenet_train
    return train(log_dir, args, hparams, input_path)
  File "/data02/zhangyb/Tacotron-2/wavenet_vocoder/train.py", line 167, in train
    model, stats = model_train_mode(args, feeder, hparams, global_step)
  File "/data02/zhangyb/Tacotron-2/wavenet_vocoder/train.py", line 117, in model_train_mode
    feeder.input_lengths, x=feeder.inputs)
  File "/data02/zhangyb/Tacotron-2/wavenet_vocoder/models/wavenet.py", line 169, in initialize
    y_hat = self.step(x, c, g, softmax=False) #softmax is automatically computed inside softmax_cross_entropy if needed
  File "/data02/zhangyb/Tacotron-2/wavenet_vocoder/models/wavenet.py", line 435, in step
    c = transposed_conv(c)
  File "/data02/zhangyb/Tacotron-2/wavenet_vocoder/models/modules.py", line 333, in __call__
    return self.convt(inputs)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 696, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/layers/convolutional.py", line 1653, in call
    data_format=utils.convert_data_format(self.data_format, ndim=4))
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1257, in conv2d_transpose
    name=name)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 805, in conv2d_backprop_input
    dilations=dilations, name=name)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Conv2DCustomBackpropInputOp only supports NHWC.
	 [[Node: model_1/inference/conv2d_transpose/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 16], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model_1/inference/conv2d_transpose/stack, model/inference/conv2d_transpose/kernel/read, model_1/inference/ExpandDims_1)]]

**Comment by v-yunbin** [comment] 2018-06-25 10:00
when train with option "tacotron2": python train.py --model='Tacotron-2'
it stuck in wavenet train:
[zhangyb@localhost Tacotron]$ tail nohup.out 
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3290, in create_op
    op_def=op_def)
  File "/data02/zhangyb/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1654, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Conv2DCustomBackpropInputOp only supports NHWC.
	 [[Node: model/inference/conv2d_transpose/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 16], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/inference/conv2d_transpose/stack, model/inference/conv2d_transpose/kernel/read, model/inference/ExpandDims_1)]]

**Comment by v-yunbin** [comment] 2018-07-23 07:14
@MXGray do you have successfully run "python synthesize.py --model='Tacotron-2' --mode='eval'"?

**Comment by Rayhane-mamah** [comment] 2018-08-04 18:41
I believe this is fixed with latest commit, if the problem persists please reopen the issue!

**Closed by Rayhane-mamah** 2018-08-04 18:41 UTC

**Comment by shartoo** [comment] 2018-08-26 06:14
Can you tell me how to fix the bug?I'm using someone else's code basing on older version of this,i can't simply replace it with current code.Thank you!
