### ISSUE TITLE
Effects on WaveNet predicted wavs

### ISSUE THREAD

**Issue by begeekmyfriend** [Rayhane-mamah/Tacotron-2#57] opened 2018-05-29 08:52 UTC
It seems the decreasing of loss during WaveNet training unsteady. Is it all right for the results or should I wait more steps? The predicted wavs under `logs-WaveNet/wavs` sound OK but the ones under `logs-WaveNet/eval-dir/wavs` sound like a mess...
![image](https://user-images.githubusercontent.com/6031938/40647939-befcb51e-635f-11e8-8901-2c30c158fc3d.png)

**Comment by Rayhane-mamah** [comment] 2018-05-29 21:20
I think it's normal that the Wavenet loss is shaky, log wavs sound better than eval wavs simply because the model is making predictions conditioned on ground truth during training, while eval wavs are synthesized sequentially which means the model is conditioned on its previous outputs. Since wavenet is still at early stages of training, conditioning on previously sampled outputs will cause loss cumulation and thus trash wavs..

**Comment by begeekmyfriend** [comment] 2018-05-30 02:09
Here are the log wav plot and the eval one. I will report again when it reaches 200K steps.
![step-95000-waveplot 2](https://user-images.githubusercontent.com/6031938/40694603-eaa02eea-63ef-11e8-9cf8-8085a5c6785f.png)
![step-95000-waveplot](https://user-images.githubusercontent.com/6031938/40694606-edda428a-63ef-11e8-9de9-a9ba640aba12.png)

**Comment by begeekmyfriend** [comment] 2018-05-31 11:28
Should the hyper parameter `train_with_GTA` be set as `True` on the training of wavenet? The wave plot still seems not good until 190K steps while in that issue https://github.com/r9y9/wavenet_vocoder/issues/79 the plot until 250K steps looks better than this one.
![step-190000-waveplot](https://user-images.githubusercontent.com/6031938/40779728-9d3471d8-6508-11e8-87f4-9fbf9186207e.png)

**Comment by butterl** [comment] 2018-05-31 12:58
@begeekmyfriend that plot in r9y9/wavenet_vocoder#79  is trained with real wav not GTA ，and GTA training wavplot for me is all mass when 50K step

**Comment by begeekmyfriend** [comment] 2018-06-06 06:38
I have used 34h `THCHS-30` as dataset long enough to train but still failed to convergence within 110K steps while in https://github.com/r9y9/wavenet_vocoder/issues/79 it seems to convergence on r9y9's version. I doubt there is something wrong with the porting...
![step-110000-waveplot](https://user-images.githubusercontent.com/6031938/41020803-ce7688d4-6996-11e8-9b75-df994b6fcae6.png)

**Comment by begeekmyfriend** [comment] 2018-06-07 02:03
This is from r9y9's original repo, on 10h dataset. We can see the wave begins to convergence.
![step000099972_waveplots](https://user-images.githubusercontent.com/6031938/41074284-edd15788-6a39-11e8-924d-bd8cff5c9217.png)

**Comment by butterl** [comment] 2018-06-07 02:28
@begeekmyfriend what‘s the step and lost in your latest post？

**Comment by azraelkuan** [comment] 2018-06-07 02:36
@begeekmyfriend what mode do u use? raw or mu-law-quantize?
i am now testing the code of wavenet, i have found that may be there are errors in incremental step.
here is training step, i am using mu-law-quantize:
![step-26000-waveplot](https://user-images.githubusercontent.com/23380152/41075240-676b2d86-6a3e-11e8-9f01-8b926d62e299.png)
but when i using incremental step:
![step-25000-waveplot](https://user-images.githubusercontent.com/23380152/41075287-8d6f0926-6a3e-11e8-8f6f-248e5daaf5e7.png)

**Comment by begeekmyfriend** [comment] 2018-06-07 02:36
![image](https://user-images.githubusercontent.com/6031938/41075279-86e86a8e-6a3e-11e8-938d-ee8b1bcdb332.png)
![image](https://user-images.githubusercontent.com/6031938/41075297-95c71cb2-6a3e-11e8-81ef-a82fb39c5f21.png)

**Comment by begeekmyfriend** [comment] 2018-06-07 02:38
I am just using the raw mode and I have not looked into the code closely.

**Comment by QLQL** [comment] 2018-06-07 14:11
The same happened to my WaveNet training (tested until step 250000 ). Note that, I used the groundtruth Mels to train the vocoder instead of these force-aligned Mels synthesised via Tacotron. 

Under logs-WaveNet/plots, the Target waveform is almost identical with Prediction waveform, this is also confirmed by listening to audio clips under logs-WaveNet/wavs. Yet, the results under logs-WaveNet/eval-dir/plot are not converged, though the envelope of the predicted signal does look similar to that of the target. However, the predicted audio clips under logs-WaveNet/eval-dir/wavs sound totally a mess---total noise.


example under logs-WaveNet/plots
![step-250000-waveplot](https://user-images.githubusercontent.com/14888000/41104607-b445c114-6a63-11e8-8b80-eb45a1b3af35.png)

example under logs-WaveNet/eval-dir/plot
![step-250000-waveplot](https://user-images.githubusercontent.com/14888000/41104635-c72e947c-6a63-11e8-9b47-d3cef1bd7306.png)

**Comment by azraelkuan** [comment] 2018-06-08 02:17
@QLQL Do u use the raw mode?

**Comment by begeekmyfriend** [comment] 2018-06-08 02:20
@QLQL Please use r9y9's original repo.

**Comment by a3626a** [comment] 2018-06-08 11:14
In my case, I am training WaveNet on mel spectrograms of SpectrogramNet with gta is on always.

I found that mel spectrograms from SpectrogramNet is really bad when gta is turned off for synthesis. This affects WaveNet's quality, too.
What mel spectrogram are you using during synthesis? STFT generated? GTA=on? GTA=off?

**Comment by QLQL** [comment] 2018-06-08 13:44
@azraelkuan Yes, I was using raw mode. But I will also test with r9r9's repo as suggested by @begeekmyfriend

**Comment by begeekmyfriend** [comment] 2018-06-09 04:06
@QLQL It failed to convergence with Rayhane's wavenet vocoder when it got to 360K steps. I trained it with batch size as 3 with 11GB GTX 1080ti.

**Comment by azraelkuan** [comment] 2018-06-11 09:12
indeed, there are servious problem in incremental step, https://github.com/Rayhane-mamah/Tacotron-2/blob/e2f9780b18648b8d0b671e1c85dd95d20d6f8553/wavenet_vocoder/models/modules.py#L162-L166
in the `while_loop`, when we call incremental_step, the queue will be defined as None, so we don't get the correct convolution queue, any way to slove the problem?

1. like the queue in the ibab's implement, we can create some different queues to save the state. not good...
2. we can use the tfe-`tensorflow eager model` to run the wavenet model, it will save the attribute in the running process. i have write a small test code and it works well.
3.use tf.get_variable to save the convolution queue

hope somebody can raise some better solutions!

**Comment by QLQL** [comment] 2018-06-11 09:29
@begeekmyfriend  I waited three days with another ~200 k steps, and there is no improvement in the loss, still between  6--7, as also shown in the following example under eval-dir/plots. I assume, maybe that has something to do with the issue mentioned by @azraelkuan ?

![step-455000-waveplot](https://user-images.githubusercontent.com/14888000/41223541-f7342e42-6d61-11e8-8c5a-77f30ee1b785.png)

**Comment by azraelkuan** [comment] 2018-06-11 10:07
@QLQL i think u can predict a wav just use the `train mode`, u will find that the predict wav is very good

**Comment by a3626a** [comment] 2018-06-15 08:54
@QLQL
Why don't you lower your learning rate? I am using 1e-4 instead of default value 1e-3. Loss is around 0.2 now. (It was 3~4 with 1e-3)

**Comment by QLQL** [comment] 2018-06-15 11:58
@a3626a , Thank you very much for the nice suggestion! Didn't think about that earlier!

**Comment by azraelkuan** [comment] 2018-06-15 15:53
@a3626a i found a much better way for this problem, we can set a input_buffer list to the while_loop, and return the input_buffer back at the incremental step, i test this, it works well.
create variable will need to assign the variable to zero but the assign function will return a op, so it is not good for coding i think.

**Comment by JK1532** [comment] 2018-06-24 04:49
@azraelkuan Have you get acceptable result after using input_buffer？And ,does the input_buffer list contains the convolution_queue for every dilation layers? Thanks

**Comment by a3626a** [comment] 2018-06-28 11:42
@JK1532 
I also fix `incremental()` by providing more variables like `input_buffer` to `tf.while_loop`. However, synthesized audio is not very good, yet.

```
    def incremental(self, initial_input, c=None, g=None,
        time_length=100, test_inputs=None,
        softmax=True, quantize=True, log_scale_min=-7.0):

        (...)

        initial_queue = self.clear_queue()
        # this returns python dictionary of empty queues for each layers.
        # {"conv0":tf.zeros(...), "conv1":tf.zeros(...)}

        (....)

        def condition(time, unused_outputs_ta, unused_current_input, unused_loss_outputs_ta, queue):
            return tf.less(time, time_length)

        def body(time, outputs_ta, current_input, loss_outputs_ta, queue):
            #conditioning features for single time step
            ct = None if self.c is None else tf.expand_dims(self.c[:, time, :], axis=1)
            gt = None if self.g_btc is None else tf.expand_dims(self.g_btc[:, time, :], axis=1)

            x = self.first_conv.incremental_step(current_input, queue)
            skips = None
            for conv in self.conv_layers:
                x, h = conv.incremental_step(x, ct, gt, queue)
                skips = h if skips is None else (skips + h)
            x = skips
            for conv in self.last_conv_layers:
                try:
                    x = conv.incremental_step(x, queue)
                except AttributeError: #When calling Relu activation
                    x = conv(x)

            #Save x for eval loss computation
            loss_outputs_ta = loss_outputs_ta.write(time, tf.squeeze(x, [1])) #squeeze time_length dimension (=1)

            #Generate next input by sampling
            if self.scalar_input:
                x = sample_from_discretized_mix_logistic(
                    tf.reshape(x, [batch_size, -1, 1]), log_scale_min=log_scale_min)
            else:
                x = tf.nn.softmax(tf.reshape(x, [batch_size, -1]), axis=1) if softmax \
                    else tf.reshape(x, [batch_size, -1])
                if quantize:
                    x = tf.reshape(x, [batch_size, -1])
                    sample = tf.multinomial(tf.reshape(x, [batch_size, -1]), 1)[0] #Pick a sample using x as probability
                    x = tf.one_hot(sample, depth=self.quantize_channels)

            outputs_ta = outputs_ta.write(time, x)
            time = time + 1
            #output = x (maybe next input)
            if test_inputs is not None:
                next_input = tf.expand_dims(test_inputs[:, time, :], axis=1)
            else:
                if is_mulaw_quantize(self.input_type):
                    next_input = tf.expand_dims(x, axis=1) #Expand on the time dimension
                else:
                    next_input = tf.expand_dims(x, axis=-1) #Expand on the channels dimension

            return (time, outputs_ta, next_input, loss_outputs_ta, queue)

        res = tf.while_loop(
            condition,
            body,
            loop_vars=[
                initial_time,
                initial_outputs_ta,
                initial_input,
                initial_loss_outputs_ta,
                initial_queue
            ],
            parallel_iterations=32,
            swap_memory=self.wavenet_swap_with_cpu)

        outputs_ta = res[1]
        #[time_length, batch_size, channels]
        outputs = outputs_ta.stack()

        #Save eval prediction for eval loss computation
        eval_outputs = res[3].stack()

        if is_mulaw_quantize(self.input_type):
            self.y_hat_eval = tf.transpose(eval_outputs, [1, 0, 2])
        else:
            self.y_hat_eval = tf.transpose(eval_outputs, [1, 2, 0])

        return tf.transpose(outputs, [1, 2, 0])
```

**Comment by azraelkuan** [comment] 2018-06-28 12:42
@JK1532 sorry, recently, i am busying with my exam.
@a3626a i think there are some problem with your code, did u check input_queue use tf.Print() in the running process, i think u should return your queue of each conv 
![image](https://user-images.githubusercontent.com/23380152/42034615-32802618-7b13-11e8-8fba-fa537911aa65.png)
![image](https://user-images.githubusercontent.com/23380152/42034794-b8a327cc-7b13-11e8-930d-20094da22fcb.png)

**Comment by a3626a** [comment] 2018-06-28 12:50
No, I don't have to. 
```
            x = self.first_conv.incremental_step(current_input, queue)
            skips = None
            for conv in self.conv_layers:
                x, h = conv.incremental_step(x, ct, gt, queue)
                skips = h if skips is None else (skips + h)
            x = skips
            for conv in self.last_conv_layers:
                try:
                    x = conv.incremental_step(x, queue)
                except AttributeError: #When calling Relu activation
                    x = conv(x)
```
`queue` is an dictionary and is modified inside `incremental_step` like `queue["conv1"] = tf.concat( ... queue["conv1"] ... )`

**Comment by Rayhane-mamah** [comment] 2018-06-28 13:21
Hello everyone, sorry for this long delay :)
@azraelkuan and @a3626a are on the right track, I actually didn't pay much attention to such embarrassing mistake.. Tensorflow doesn't really work with python semantic especially not in its while loop. all the code we make is typically for a graph construction so it is only executed once (except for the tf.while_loop). The mistake I was making is that I was expecting tensorflow to update a class attribute when executing loops but that was not the case obviously, so I suspect a dictionary update can have the same issue @a3626a. Anyway, I will naturally make an update of the repo this weed end to fix this issue and many others, but just because this one is critical and can be corrected right away (without the need to retrain the model), Here are the **wavenet.py** and **modules.py** files you need for a correct fast wavenet synthesis:

[models.tar.gz](https://github.com/Rayhane-mamah/Tacotron-2/files/2145382/models.tar.gz)

it should be possible to just correct the incremental steps without retraining the model, it's mostly a synthesis time bug. It is also not mandatory to provide convolution queues to all network convolutions, only the dilated convolutions of the residual blocks need them (kernel_size=3). Queues are initialized to zeros before the while loop and are simply shifted at each iteration. Naturally they are provided as inputs and picked as outputs for these convolutions.

If using already trained models, do NOT replace your existing files with these ones, I may have changed some scopes so they will raise errors, instead just pick the "argmax" rectification, while_loop and the new conv1d incremental_step updates (__init__ too has changed). 

One last detail, during training, Ryuichi's Wavenet paddings with our conv1d __call__ function raises problems for the reshape to dilated convolutions, almost everytime except when hop_size is power of 2 (that was the problem if I'm not wrong). Fast Wavenet's padding on the other hand is using paddings that only works for the special case of kernel_size=2, In the above files I updated fast wavenet's padding technique to support any kernel_size (2 and higher) while allowing to use any arbitrary hop size with Wavenet (for my case I use n_fft=2048, hop_size=300, win_size=1200 and sample_rate=24kHz without problems). Thanks for all your efforts!

**Comment by a3626a** [comment] 2018-06-28 13:40
@Rayhane-mamah 
I already synthesized intelligible audio using dictionary based implementation.

**Comment by Rayhane-mamah** [comment] 2018-06-28 13:51
@a3626a, ah perfect then ignore me :) I only tested the list approach so I only can confirm that list approach works, dictionaries one is cleaner I think, I'll have a look into it, thanks @a3626a ;)

**Comment by azraelkuan** [comment] 2018-06-28 13:53
@Rayhane-mamah why not just use the tf.layers.Conv1d 's dilation_rate?

**Comment by azraelkuan** [comment] 2018-06-28 13:58
![image](https://user-images.githubusercontent.com/23380152/42038790-668b5d78-7b1e-11e8-9f2d-0d8e3dc560e6.png)
![image](https://user-images.githubusercontent.com/23380152/42038816-6c021ba2-7b1e-11e8-8cf9-febaf27f4b8a.png)
this is my code

**Comment by Rayhane-mamah** [comment] 2018-06-28 14:05
@azraelkuan,
It should give exact same results during training actually, and I would have preferred to use that. unfortunately, I think I found some issues for picking the kernels and biases of such layer for inference time (to use the fast wavenet synthesis approach). If I remember well, I was facing some issue where at inference time the kernel and bias variables where only being initialized at the **build** function call of the convolution layer and it wasn't working with how I make my Wavenet code structure or something like that. In other words I just found it easier to create and use my own kernel and bias variables. 
Plus I was kind of worried that using tf.layers.Conv1D would some way or another not work as I expect them to be.. So it's also a safety measure I took to make sure the network is as I'm thinking of it. I went to a lower level and used tf.nn.conv1d with our own kernel and bias variables to "rewrite" tf.layers.Conv1D if both give the same results.

When using tf.layers.Conv1D, are you able to get its kernel and bias without problem during synthesis mode?

**Comment by azraelkuan** [comment] 2018-06-28 14:14
yes, i also have the same issue, but i can get the kernel and bias by the collections. because of tensorflow will save all the variables in tf.GraphKeys.GLOBAL_VARIABLES, so we can get it by scope.
this is a better way to implement this.
![image](https://user-images.githubusercontent.com/23380152/42039639-71783f74-7b20-11e8-8f4f-878c2c41545f.png)

**Comment by Rayhane-mamah** [comment] 2018-06-28 14:46
Ah yes this is very clever @azraelkuan! Really well thought! I will try it out for train+eval and synthesis time, if everything goes well and results are also correct I will most probably switch to this approach. If you get samples in the meantime using your code, feel free to share and suggest a PR ;)

**Comment by azraelkuan** [comment] 2018-06-28 15:20
@Rayhane-mamah yeah，i have finish my exam, so i will fix the bugs in my code these days. :)

**Comment by HyperGD1994** [comment] 2018-07-03 01:53
@Rayhane-mamah hi, i'm training the WaveNet with your revised code, feeding raw audio input and the eval result seems not good at 20k steps. i wonder if it will be good to train more steps?

Meanwhile, i have trained the ibab's wavenet with local condition, mu-quantize audio and mel-spec input, and it can generate correct audio after a days training.  i'm not satisfied with the acoustic quality so i try to use your code, raw input and bigger net.  

i'm confused about the eval result, is the revised still not right or i just need to train it more steps? thanks ~

**Comment by azraelkuan** [comment] 2018-07-03 03:01
@HyperGD1994 yes, there is problem in the eval code, i try to fix the bugs, but like @a3626a, still can not get good result.

**Comment by HyperGD1994** [comment] 2018-07-03 03:58
@azraelkuan have you tried [ibab's](https://github.com/ibab/tensorflow-wavenet) generate method, will that be more brief?

**Comment by butterl** [comment] 2018-07-03 04:11
@azraelkuan 

I found it gives good result wav in training sample

![image](https://user-images.githubusercontent.com/3068190/42198354-19a91e74-7eba-11e8-9c2e-b7fb2a62585c.png)

and would stuck when run synthesize

in synthesizer.py in wavnet_vocoder
```
	def synthesize(self, mel_spectrogram, speaker_id, index, out_dir, log_dir):
		hparams = self._hparams
		local_cond, global_cond = self._check_conditions()

		c = mel_spectrogram
		g = speaker_id
		feed_dict = {}
		print("Hi I'm here")
		if local_cond:
			feed_dict[self.local_conditions] = [np.array(c, dtype=np.float32)]
		else:
			feed_dict[self.synthesis_length] = 100
		print("Hi I'm here 2")
		if global_cond:
			feed_dict[self.global_conditions] = [np.array(g, dtype=np.int32)]

		generated_wav = self.session.run(self.model.y_hat, feed_dict=feed_dict)   <<< stucked here
		print("Hi I'm here 3")
```

**Comment by begeekmyfriend** [comment] 2018-07-03 06:15
@azraelkuan @butterl Can you open your fork for every one interested in it?

**Comment by HyperGD1994** [comment] 2018-07-03 06:17
@azraelkuan wow that's wonderful, may i ask how many steps have you trained to get this? do you input only mel spec or with audio file too?

**Comment by azraelkuan** [comment] 2018-07-03 06:19
@HyperGD1994 this result use test inputs,only 1500 steps, i am testing the real evaluating step

**Comment by butterl** [comment] 2018-07-04 02:43
@begeekmyfriend  @HyperGD1994  I used the Head of repo and just suit for THCHS30 dataset， and the waveplot is from the eval in the training of wavenet,  the training step of tacotron is 100k and wavenet 160K

@azraelkuan  any suggestion on  real evaluating step modification ? I can only see it stuck in tqdm 0%

**Comment by v-yunbin** [comment] 2018-07-23 06:40
@butterl i have same problem with you, do you have solve it?

**Comment by UESTCgan** [comment] 2018-07-25 01:18
@azraelkuan @begeekmyfriend@HyperGD1994  I also encountered the same problem. Do you have the final solution? Looking forward to your help。

**Comment by Yeongtae** [comment] 2018-07-25 07:01
Has anyone found a solution?
Even if you do not release your code, please share results and ideas, how to fix it.

**Comment by HyperGD1994** [comment] 2018-07-25 08:09
@UESTCgan what's your problem? tqdm 0%?  I do not use the whole code, i just use part of it, so i did not encounter this problem, but i think this bug will not be difficult to fix, you can try to debug it.

as for the **true evaluate problem**, have @azraelkuan fix it? the raw input is so hard to train, and the mu-law input seems to have a lot of bugs. However, i modified [ibab](https://github.com/ibab/tensorflow-wavenet) code with local condition and a bigger net, and i finally got wonderful result with mu-law input. I suggest that you guys can try that.

**Comment by azraelkuan** [comment] 2018-07-25 08:15
Indeed, the answer has been given https://github.com/Rayhane-mamah/Tacotron-2/files/2145382/models.tar.gz, because training a mol model need much time about two weeks, so i don't test this, but in my test, the mu law works well.
below is the plot of mu law (eval step)
![image](https://user-images.githubusercontent.com/23380152/43188115-f0054638-9025-11e8-9389-236ac0f5d32b.png)

**Comment by Yeongtae** [comment] 2018-07-26 01:02
@azraelkuan Thank you for your answer.

**Comment by UESTCgan** [comment] 2018-07-27 03:35
@HyperGD1994 Thank for your help!Based on my current 20h Chinese data set, I have trained 240K times. The predicted values produced during training sound good, but only noise is obtained when synthesizing sound. I will try the latest code next.

**Comment by Yeongtae** [comment] 2018-07-27 06:36
@azraelkuan Did you test in LJspeech dataset?
 If you test it, How many iterations have you learned to get the above result?

**Comment by azraelkuan** [comment] 2018-07-27 06:44
@Yeongtae about 40k, i can generate good wav, above is about 300k.
attached is 44k.
[44000.zip](https://github.com/Rayhane-mamah/Tacotron-2/files/2234756/44000.zip)

**Comment by Yeongtae** [comment] 2018-07-27 08:57
I had a mistake. 
I didn't change a value of quantize_channels in hparams.py
![image](https://user-images.githubusercontent.com/13597229/43311337-223d8c14-91c5-11e8-983e-733fd4b1732c.png)

I'm testing with the parameters in above images. 
I can see that the model is reducing loss.

**Comment by Rayhane-mamah** [comment] 2018-08-04 18:34
Thank you all for your valuable contributions, this issue has been fixed with latest commit. If any further problems appear, feel free to open new issues :)

**Closed by Rayhane-mamah** 2018-08-04 18:34 UTC
