### ISSUE TITLE
Training with multi-GPUs

### ISSUE THREAD

**Issue by sandu1840cmc** [Rayhane-mamah/Tacotron-2#151] opened 2018-08-13 14:42 UTC
Hi Rayhane,

I have one question that why cannot run with multi-GPUs? In hpara.py file, I set use_all_gpus to "True", but it seems that only one GPU is used during training process.  (I have 4 GPUs but only gpu:0 can be used).

#Hardware setup (TODO: multi-GPU parallel tacotron training)
	use_all_gpus = True, #Whether to use all GPU resources. If True, total number of available gpus will override num_gpus.
	num_gpus = 2, #Determines the number of gpus in use

**Comment by gsoul** [comment] 2018-08-13 20:41
Please kindly take a look here, this question has already been discussed a few times in closed issues:
https://github.com/Rayhane-mamah/Tacotron-2/issues/43

In short: those config options do not work so far. But there is a fork of this repo that claims to support multi-gpu training.

**Comment by Rayhane-mamah** [comment] 2018-08-13 21:30
Hello @sandu1840cmc thanks for reaching out!

Like @gsoul said, this is a duplicate of (https://github.com/Rayhane-mamah/Tacotron-2/issues/43). We actually do not support multi-gpu and we didn't have much success with it on Tacotron model (we didn't notice any major speed of training/speed of convergence difference). If you're still interested in using multi-gpu training, please refer to [this fork](https://github.com/MlWoo/Tacotron-2) where they use multi-gpu. The code is a little outdated but you can still apply their multi-gpu tricks to our work if needed.

I hope this answers your questions. :)

**Closed by Rayhane-mamah** 2018-08-13 21:30 UTC

**Comment by sandu1840cmc** [comment] 2018-08-14 01:14
Thanks a lot for your explanation. I will try it later :)
